---
- project:
    name: aai-test-config
    project-name: 'aai-test-config'
    jobs:
      - gerrit-maven-clm
    project: 'aai/test-config'
    stream:
      - 'master':
          branch: 'master'
    mvn-settings: 'aai-test-config-settings'
    files: '**'
    archive-artifacts: ''
    build-node: ubuntu1604-basebuild-4c-4g
