---
- project:
    name: integration-docker-onap-java-info
    project-name: integration-docker-onap-java
    jobs:
      - gerrit-info-yaml-verify
    build-node: centos8-builder-2c-1g
    project: integration/docker/onap-java11
    branch: master

- project:
      name: integration-docker-onap-java-linters
      project: integration/docker/onap-java11
      project-name: integration-docker-onap-java
      python-version: python3
      jobs:
          - integration-linters
      subproject:
          - 'yaml':
                tox-dir: '.'
                tox-envs: 'yaml'
                pattern: '**/*.yaml'
          - 'yml':
                tox-dir: '.'
                tox-envs: 'yaml'
                pattern: '**/*.yml'
          - 'json':
                tox-dir: '.'
                tox-envs: 'json'
                pattern: '**/*.json'
          - 'md':
              tox-dir: '.'
              tox-envs: 'md'
              pattern: '**/*.md'
      stream:
          - 'master':
                branch: 'master'

- project:
    name: integration-docker-onap-java-release
    project-name: 'integration-docker-onap-java'
    project: 'integration/docker/onap-java11'
    mvn-settings: 'integration-settings'
    jobs:
      - '{project-name}-gerrit-release-jobs':
          build-node: centos7-docker-2c-1g

- project:
    name: 'integration-docker-onap-java-docker'
    jobs:
      - gerrit-docker-verify:
          project-name: 'integration-docker-onap-java11'
          docker-name: 'onap/integration-java11'
      - gerrit-docker-merge:
          project-name: 'integration-docker-onap-java11'
          docker-name: 'onap/integration-java11'
      - gerrit-docker-verify:
          project-name: 'integration-docker-onap-java17'
          docker-name: 'onap/integration-java17'
          docker-build-args: '--build-arg java_ver=onap-java17'
      - gerrit-docker-merge:
          project-name: 'integration-docker-onap-java17'
          docker-name: 'onap/integration-java17'
          docker-build-args: '--build-arg java_ver=onap-java17'
    project: 'integration/docker/onap-java11'
    stream:
      - 'master':
            branch: 'master'
            files: ''
    docker-root: '$WORKSPACE'
    mvn-settings: 'integration-settings'
    build-node: ubuntu1804-docker-8c-8g
