---
- project:
    name: integration-docker-onap-java11-info
    project-name: integration-docker-onap-java11
    jobs:
      - gerrit-info-yaml-verify
    build-node: centos7-builder-2c-1g
    project: integration/docker/onap-java11
    branch: master

- project:
      name: integration-docker-onap-java11-linters
      project: integration/docker/onap-java11
      project-name: integration-docker-onap-java11
      python-version: python3
      jobs:
          - integration-linters
      subproject:
          - 'yaml':
                tox-dir: '.'
                tox-envs: 'yaml'
                pattern: '**/*.yaml'
          - 'yml':
                tox-dir: '.'
                tox-envs: 'yaml'
                pattern: '**/*.yml'
          - 'json':
                tox-dir: '.'
                tox-envs: 'json'
                pattern: '**/*.json'
          - 'md':
              tox-dir: '.'
              tox-envs: 'md'
              pattern: '**/*.md'
      stream:
          - 'master':
                branch: 'master'

- project:
    name: integration-docker-onap-java11-release
    project-name: 'integration-docker-onap-java11'
    project: 'integration/docker/onap-java11'
    mvn-settings: 'integration-settings'
    jobs:
      - '{project-name}-gerrit-release-jobs':
          build-node: centos7-docker-8c-8g

- project:
    name: 'integration-docker-onap-java11-docker'
    jobs:
      - gerrit-docker-verify
      - gerrit-docker-merge
    project-name: 'integration-docker-onap-java11'
    project: 'integration/docker/onap-java11'
    stream:
      - 'master':
            branch: 'master'
            files: ''
    docker-name: 'onap/integration-java11'
    docker-build-args: '-f ./Dockerfile'
    docker-root: '$WORKSPACE'
    mvn-settings: 'integration-settings'
    build-node: ubuntu2004-docker-8c-8g
