---
- import_playbook: ../common-packer/provision/docker.yaml

- hosts: all
  become_user: root
  become_method: sudo

  vars:
    kubectl_version: 1.19.11
    helm3_6_version: 3.6.3
    chartmuseum_version: 0.12.0

  tasks:
    - name: 'Install kubectl {{kubectl_version}}'
      get_url:
        url: "https://storage.googleapis.com/kubernetes-release/release/v{{kubectl_version}}/bin/linux/amd64/kubectl"
        dest: /usr/local/bin/kubectl
        mode: 0775
      become: yes

    - name: 'Install Helm3.6 {{helm3_6_version}}'
      block:
        - name: 'Create directory /tmp/helm3.6'
          file:
            path: /tmp/helm3.6
            state: directory
        - name: 'Fetch tar.gz for Helm 3.6'
          get_url:
            url: "https://get.helm.sh/helm-v{{helm3_6_version}}-linux-amd64.tar.gz"
            dest: /tmp/helm3.6
        - name: 'Unarchive Helm 3.6'
          unarchive:
            src: "/tmp/helm3.6/helm-v{{helm3_6_version}}-linux-amd64.tar.gz"
            dest: /tmp/helm3.6
            remote_src: true
          become: yes
        - name: 'Move Helm 3.6 bin to /usr/local/bin and set as executable'
          command: 'mv /tmp/helm3.6/linux-amd64/helm /usr/local/bin/helm3.6'
          become: yes
        - name: 'Check Helm 3.6'
          command: 'which helm3.6'
        - name: 'Check kubectl {{kubectl_version}}'
          command: 'which kubectl'

        - name: 'Install Helm 3.6'
          shell: |
             echo "----> Installing helm3.6"
             wget 'https://get.helm.sh/helm-v{{helm3_6_version}}-linux-amd64.tar.gz'
             tar -xvf 'https://get.helm.sh/helm-v{{helm3_6_version}}-linux-amd64.tar.gz'
             mv linux-amd64/helm /usr/local/bin/helm3.6
             which helm3.6
          become: true

    - name: 'Install ChartMuseum {{chartmuseum_version}}'
      block:
        - name: 'Fetch bin for ChartMuseum'
          get_url:
            url: "https://s3.amazonaws.com/chartmuseum/release/v{{ chartmuseum_version }}/bin/linux/amd64/chartmuseum"
            dest: /usr/local/bin/chartmuseum
            mode: "0755"
          become: yes
        - name: 'Check ChartMuseum {{chartmuseum_version}}'
          command: 'which chartmuseum'
