---
- import_playbook: ../common-packer/provision/baseline.yaml

- hosts: all
  become_user: root
  become_method: sudo

  roles:
    - fkautz.kubernetes-install
    - andrewrothstein.kubernetes-helm

