---
- import_playbook: ../common-packer/provision/docker.yaml

- hosts: all
  become_user: root
  become_method: sudo
  vars:
    apt_file: /etc/apt/sources.list.d/google-chrome.list
    docker_compose_version: 1.17.1
    glide_checksum: sha256:c403933503ea40308ecfadcff581ff0dc3190c57958808bb9eed016f13f6f32c
    glide_version: v0.13.1
    golang_version: 1.9.1

  tasks:
    - name: "Checking for x86_64"
      set_fact:
        host_arch: "amd64"
        golang_checksum: sha256:07d81c6b6b4c2dcf1b5ef7c27aaebd3691cdb40548500941f92b221147c5d9c7
      when: "'x86_64' in ansible_architecture"

    - name: "Checking for aarch64"
      set_fact:
        host_arch: "arm64"
        golang_checksum: sha256:d31ecae36efea5197af271ccce86ccc2baf10d2e04f20d0fb75556ecf0614dad
      when: "'aarch64' in ansible_architecture"

    - name: 'Install Docker Compose {{docker_compose_version}}'
      command: curl -o /usr/local/bin/docker-compose -L "https://github.com/docker/compose/releases/download/{{docker_compose_version}}/docker-compose-Linux-x86_64"
      become: true

    - file:
        path: /usr/local/bin/docker-compose
        mode: "+x"
      become: true

    - name: 'Install GoLang {{golang_version}}'
      block:
        - name: 'Fetch golang {{golang_version}} to /tmp/go{{golang_version}}.linux-{{host_arch}}.tar.gz'
          get_url:
            url: 'https://storage.googleapis.com/golang/go{{golang_version}}.linux-{{host_arch}}.tar.gz'
            dest: '/tmp/go{{golang_version}}.linux-{{host_arch}}.tar.gz'
            checksum: '{{golang_checksum}}'
        - name: 'Install golang {{golang_version}} to /usr/local'
          unarchive:
            src: '/tmp/go{{golang_version}}.linux-{{host_arch}}.tar.gz'
            dest: /usr/local
            remote_src: true
          become: true
        - name: Create symbolic link to go bin
          file:
            src: "/usr/local/go/bin/go"
            dest: "/usr/bin/go"
            state: link
          become: true

    - name: Install libxml2-utils
      apt:
        name: libxml2-utils
        state: present
      become: true

    - name: Install python-tox
      apt:
        name: python-tox
        state: present
      become: true

    - apt_repository:
        repo: ppa:jonathonf/python-3.6
        state: present
      become: true

    - name: Update and upgrade apt packages
      apt:
        upgrade: yes
        update_cache: yes
      become: true

    - name: Install Python 3.6 and packages
      apt:
        name:
          - python3.6
          - python3.6-dev
          - libssl-dev
          - libmysqlclient-dev
          - gcc
      become: true

    - name: Install base packages
      apt:
        name:
          - unzip
          - xz-utils
          - libxml-xpath-perl
          - wget
          - make
          - npm
          - sshuttle
          - netcat
          - libssl-dev
          - libffi-dev
      become: true

    - name: Install autorelease support packages
      apt:
        name:
          - xmlstarlet
          - xvfb
          - crudini
          - maven
          - python-ncclient
      become: true

    - name: Add Google Chrome key
      apt_key:
        url: https://dl-ssl.google.com/linux/linux_signing_key.pub
        state: present
      become: true
      when: "'x86_64' in ansible_architecture"

    - name: Add Google Chrome repo
      copy: content="deb http://dl.google.com/linux/chrome/deb/ stable main" dest={{apt_file}} owner=root group=root mode=644
      become: true
      when: "'x86_64' in ansible_architecture"

    - name: Update apt cache
      apt: update_cache=yes
      become: true

    - name: Install Google Chrome
      apt:
        name: google-chrome-stable
        state: present
      become: true
      when: "'x86_64' in ansible_architecture"

    - name: Install Erlang dependency packages
      apt:
        name:
          - libwxgtk3.0-0v5
          - libsctp1
          - libwxbase3.0-0v5
      become: true
      when: "'x86_64' in ansible_architecture"

    - name: Install Erlang
      apt:
        deb: https://packages.erlang-solutions.com/erlang/esl-erlang/FLAVOUR_1_general/esl-erlang_19.3.6-1~ubuntu~trusty_amd64.deb
      install_recommends: yes
      become: true
      when: "'x86_64' in ansible_architecture"

    - name: Clone rebar3
      git:
        repo: 'https://github.com/erlang/rebar3.git'
        dest: /tmp/rebar3
      when: "'x86_64' in ansible_architecture"

    - name: Bootstrap rebar3
      command: ./bootstrap
      args:
        chdir: /tmp/rebar3
      when: "'x86_64' in ansible_architecture"

    - name: Install rebar3 to bin
      copy:
        src: /tmp/rebar3/rebar3
        dest: /usr/bin/rebar3
        mode: 0755
        remote_src: true
      become: true
      when: "'x86_64' in ansible_architecture"

    - name: Remove unused rebar3 source
      file:
        path: /tmp/rebar3
        state: absent
      when: "'x86_64' in ansible_architecture"

    - name: Download geckodriver
      unarchive:
        src: https://github.com/mozilla/geckodriver/releases/download/v0.18.0/geckodriver-v0.18.0-linux64.tar.gz
        dest: /usr/bin
        mode: 0755
        remote_src: yes
      become: true
      when: "'x86_64' in ansible_architecture"

    - name: Download Firefox version 55.0.3
      unarchive:
        src: https://download-installer.cdn.mozilla.net/pub/firefox/releases/55.0.3/linux-x86_64/en-US/firefox-55.0.3.tar.bz2
        dest: /opt
        mode: 0755
        remote_src: yes
      when: "'x86_64' in ansible_architecture"
      become: true

    - name: Create symbolic link to firefox bin
      file:
        src: "/opt/firefox/firefox"
        dest: "/usr/bin/firefox"
        state: link
      when: "'x86_64' in ansible_architecture"
      become: true
