---
- import_playbook: ../common-packer/provision/baseline.yaml

- hosts: all
  become_user: root
  become_method: sudo

  tasks:
    - name: 'Install Memcached'
      command: apt-get install memcached
      become: true
