---
- import_playbook: ../common-packer/provision/baseline.yaml

- hosts: all
  become_user: root
  become_method: sudo

  tasks:
    - name: 'Install Redis'
      package:
        name: redis
        state: present
      become: true

    - name: 'Enable service redis'
      service:
        name: redis
        enabled: yes
      become: true

    - name: 'Start service redis'
      service:
        name: redis
        state: started
      become: true

    - name: Install Python dependency packages for mysqlclient
      yum:
        name:
          - python-devel
          - mysql-devel
          - python3-devel
        state: latest
      become: yes