---
- project:
    name: so-docker-config
    project-name: 'so-docker-config'
    project: 'so/docker-config'
    stream:
      - 'master':
          branch: 'master'
    mvn-settings: 'so-docker-config-settings'
    files: '**'
    archive-artifacts: ''
