---
- project:
      name: dcaegen2-platform-ves-openapi-manager
      project-name: 'dcaegen2-platform-ves-openapi-manager'
      java-version: openjdk11
      jobs:
          - '{project-name}-{stream}-verify-java'
          - '{project-name}-{stream}-merge-java'
          - gerrit-maven-stage:
                sign-artifacts: true
                build-node: centos7-docker-8c-8g
                maven-versions-plugin: true
          - gerrit-maven-docker-stage:
                build-node: ubuntu1804-docker-8c-8g
                container-public-registry: 'nexus3.onap.org:10001'
                container-staging-registry: 'nexus3.onap.org:10003'
                mvn-goals: 'clean package docker:build -DpushImageTag'
          - '{project-name}-gerrit-release-jobs':
                build-node: centos7-docker-8c-8g

      project: 'dcaegen2/platform/ves-openapi-manager'
      stream:
          - 'master':
                branch: 'master'
      mvn-settings: 'dcaegen2-platform-ves-openapi-manager-settings'
      # due to a strange macro / variable translation problem this needs
      # to be passed as a string block to properly get the properties
      # correctly defined in the job
      maven-deploy-properties: |
          deployAtEnd=true
      files: '**'
      archive-artifacts: ''
      build-node: 'ubuntu1804-docker-8c-8g'

- project:
      name: dcaegen2-platform-ves-openapi-sonar
      java-version: openjdk11
      jobs:
          - gerrit-maven-sonar
      sonarcloud: true
      sonarcloud-project-organization: '{sonarcloud_project_organization}'
      sonarcloud-api-token: '{sonarcloud_api_token}'
      sonarcloud-project-key: '{sonarcloud_project_organization}_{project-name}'
      sonar-mvn-goal: '{sonar_mvn_goal}'
      cron: '@daily'
      build-node: ubuntu1804-docker-8c-8g
      project: 'dcaegen2/platform/ves-openapi-manager'
      project-name: 'dcaegen2-platform-ves-openapi-manager'
      branch: 'master'
      mvn-settings: 'dcaegen2-platform-ves-openapi-manager-settings'
      mvn-goals: 'clean install'
      mvn-opts: '-Xmx1024m -XX:MaxPermSize=256m'


- project:
    name: dcaegen2-platform-ves-openapi-manager-project-view
    project-name: dcaegen2-platform-ves-openapi-manager
    views:
      - project-view

- project:
    name: dcaegen2-platform-ves-openapi-manager-info
    project: dcaegen2/platform/ves-openapi-manager
    project-name: dcaegen2-platform-ves-openapi-manager
    build-node: centos7-builder-2c-1g
    jobs:
      - gerrit-info-yaml-verify
