DOCKER_REGISTRY=nexus3.onap.org
DOCKERHUB_REGISTRY=docker.io
GERRIT_URL=https://gerrit.onap.org/r
GIT_BASE=ssh://ecomp-jobbuilder@gerrit.onap.org:29418/$PROJECT
GIT_NO_PROJECT=ssh://ecomp-jobbuilder@gerrit.onap.org:29418
GIT_URL=ssh://ecomp-jobbuilder@gerrit.onap.org:29418
JENKINS_HOSTNAME=vex-yul-ecomp-jenkins-2
JIRA_URL=https://jira.onap.org
LOGS_REPO_URL=https://nexus.onap.org/service/local/repositories/logs
LOGS_SERVER=https://logs.onap.org
NEXUS_URL=https://nexus.onap.org
NEXUSPROXY=https://nexus.onap.org
REGISTRY_PORTS=10001 10002 10003 10004
SILO=sandbox
SONAR_URL=https://sonar.onap.org
